# Generated by Django 5.2.4 on 2025-08-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
